title: BSA Troop 370
url: "https://troop370atlanta.org"
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  style: compressed
  load_paths:
    - _scss
    - node_modules
exclude:
  - vendor
  - node_modules
  - js/main(source).js
  - js/cibuild
include:
  - node_modules/@material
collections:
  about:
    output: true
    permalink: /:path.html
  information:
    output: true
    permalink: /information/:path.html
  events:
    output: true
    permalink: /events/:path.html
  members:
    output: true
    permalink: /members/:path.html
  photos:
    output: true
    permalink: /:path.html
  contact:
    output: true
    permalink: /:path.html
  payments:
    output: true
    permalink: /pay/:path.html
  store:
    output: true
    permalink: /pay/:path.html
collections_dir: _collections
