title: BSA Troop 370
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-relative-links
sass:
  load_paths:
    - _scss
    - node_modules
exclude:
  - vendor
  - node_modules
include:
  - node_modules/@material
