title: BSA Troop 370
site: "https://troop370atlanta.org"
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  style: compressed
  load_paths:
    - _scss
    - node_modules
exclude:
  - vendor
  - node_modules
  - js/main(source).js
  - js/cibuild
include:
  - node_modules/@material
collections:
  about:
    output: true
  information:
    output: true
  events:
    output: true
  members:
    output: true
  contact:
    output: true
    permalink: /:path
